framework:
    secret: "%secret%"
    router:
        resource: .
        type: dynamic
        utf8: true
    form: false
    validation:
        enable_annotations: true
    translator:
        fallback: en
    default_locale: "%locale%"
    session:
        handler_id: "claroline.session_handler.file" # Overridden by SessionConfigPass
        cookie_httponly: true
        cookie_secure: auto
        cookie_samesite: "%claroline.session_cookie_samesite%"
    cache: ~
    php_errors:
        log: true
