plugin:
    resource_actions:
        # Opens a resource
        - name: open
          decoder: open
          scope: [object]
          default: true # This is the default action of the resource (it SHOULD NOT be overridden)
          api: [GET]

        # Displays common resources info (the one from the node)
        - name: about
          decoder: open
          scope: [object]
          api: [GET]

        # Changes changes the content of a resource
        - name: edit
          decoder: edit
          group: management
          scope: [object]
          api: [PUT]

        # Changes and manages the rights of a resource
        - name: rights
          decoder: administrate
          group: management
          scope: [object, collection]
          api: [GET, POST]

        # Publishes one ore more resources
        - name: publish
          decoder: administrate
          group: management
          scope: [object, collection]
          api: [PUT]

        # Unpublishes one ore more resources
        - name: unpublish
          decoder: administrate
          group: management
          scope: [object, collection]
          api: [PUT]

        # Exports one or more resources in a Claroline format (archive + manifest)
        - name: export
          decoder: export
          group: transfer
          scope: [object, collection] # The action can be executed on multiple resources at once.
          api: [GET]
          recursive: true

        # Deletes a one or more resources
        - name: delete
          decoder: delete
          group: management
          scope: [object, collection] # The action can be executed on multiple resources at once.
          api: [DELETE]
          recursive: true

        # Changes common resources info (the one from the node) for one or more resources
        - name: configure
          decoder: administrate
          group: management
          scope: [object, collection] # The action can be executed on multiple resources at once.
          api: [PUT]
          recursive: true

        # Creates a copy of one or more resources
        - name: copy
          decoder: administrate
          group: management
          scope: [object, collection] # The action can be executed on multiple resources at once.
          api: [POST]
          recursive: true

        # Changes the parent of one or more resources
        - name: move
          decoder: administrate
          group: management
          scope: [object, collection] # The action can be executed on multiple resources at once.
          api: [PUT]
          recursive: true

        # Displays tracking info about the resource
        - name: logs
          decoder: administrate # todo : adds it's own right
          scope: [object]
          api: [GET]

        - name: notes
          decoder: open
          scope: [object]
          api: [GET, POST, PUT, DELETE]

    resources:
        - name: file
          class: Claroline\CoreBundle\Entity\Resource\File
          tags: [content]
          exportable: true
          actions:
              - name: download
                decoder: export
                group: transfer
                api: [GET]

        - name: directory
          class: Claroline\CoreBundle\Entity\Resource\Directory
          tags: [structure]
          exportable: true
          actions:
              # Creates a new resource in the directory
              - name: add
                decoder: create
                group: management
                api: [POST]

              # Imports one or more resources in the directory
              - name: import
                decoder: create
                group: transfer
                api: [POST]

        - name: text
          class: Claroline\CoreBundle\Entity\Resource\Text
          tags: [content]
          exportable: true

        - name: activity
          class: Claroline\CoreBundle\Entity\Resource\Activity

    admin_tools:
        - name: platform_parameters
          class: cog

        - name: user_management
          class: user

        - name: workspace_management
          class: book

        - name: registration_to_workspace
          class: book

        - name: desktop_and_home
          class: home

        # todo move as desktop tool
        - name: platform_logs
          class: line-chart

        # todo move as desktop tool
        - name: platform_analytics
          class: pie-chart

        - name: widgets_management
          class: list-alt

        - name: tasks_scheduling
          class: clock-o

        - name: data_transfer
          class: exchange

    widgets:
        #- name: core_resource_logger
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: simple_text
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: my_workspaces
        #      is_configurable: false
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: false
        #- name: my_profile
        #      is_configurable: false
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: false
        #- name: resources_widget
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: resource_text
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true

        - name: simple
          class: Claroline\CoreBundle\Entity\Widget\Type\SimpleWidget
          context: [workspace, desktop]
          tags: [content]

        - name: list
          class: Claroline\CoreBundle\Entity\Widget\Type\ListWidget
          abstract: true

        - name: profile
          class: Claroline\CoreBundle\Entity\Widget\Type\ProfileWidget
          context: [workspace, desktop]
          tags: [users]

        - name: resource-list
          parent: list
          context: [workspace, desktop]
          tags: [resources]

        - name: user-list
          parent: list
          context: [workspace, desktop]
          tags: [users]

        - name: workspace-list
          parent: list
          context: [desktop]
          tags: [workspaces]

    tools:
        - name: home
          class: home
          is_displayable_in_workspace: true
          is_displayable_in_desktop: true
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: true
          is_locked_for_admin: false
          is_anonymous_excluded: false

        - name: resource_manager
          class: folder
          is_displayable_in_workspace: true
          is_displayable_in_desktop: true
          is_configurable_in_workspace: true
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: true
          is_locked_for_admin: false
          is_anonymous_excluded: false

        - name: logs
          class: line-chart
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true

        - name: analytics
          class: pie-chart
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true

        - name: users
          class: user
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: true
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true

        - name: my_contacts
          class: address-book
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true

    themes:
        - name: Claroline
        - name: Claroline Black
        - name: Claroline Mint
        - name: Claroline Ruby
