# This file contains the core container parameters.
parameters:
    # Project base paths
    claroline.param.root_directory:         "%kernel.root_dir%/.."
    claroline.param.config_directory:       "%kernel.root_dir%/config"
    claroline.param.vendor_directory:       "%claroline.param.root_directory%/vendor"
    claroline.param.web_directory:          "%claroline.param.root_directory%/web"

    # File paths
    claroline.param.uploads_directory:      "%claroline.param.web_directory%/uploads"
    claroline.param.files_directory:        "%claroline.param.root_directory%/files"
    claroline.param.archive_directory:      "%claroline.param.files_directory%/archives"
    claroline.param.public_files_directory: "%claroline.param.files_directory%/data"
    claroline.param.icon_sets_directory:    "%claroline.param.public_files_directory%/icon_sets"
    claroline.param.data_web_dir:           "%claroline.param.web_directory%/data"
    claroline.param.icon_sets_web_dir:      "%claroline.param.data_web_dir%/icon_sets"

    # Log paths
    claroline.param.log_dir:           "%kernel.root_dir%/logs/"
    claroline.param.import_log_dir:    "%claroline.param.log_dir%/transfer"
    claroline.param.workspace_log_dir: "%claroline.param.log_dir%/workspace"

    # Configuration provider
    claroline.param.platform_config_handler_class: "Claroline\\CoreBundle\\Library\\Configuration\\PlatformConfigurationHandler"
    claroline.param.platform_options:              "%claroline.param.config_directory%/platform_options.json"

    # Base workspace model path
    claroline.param.workspace.default: "%claroline.param.vendor_directory%/claroline/distribution/main/core/Resources/config/workspace.zip"

    # IP config files (should be stored in DB)
    claroline.param.ip_white_list_file:       "%kernel.root_dir%/config/ip_white_list.yml"
    claroline.param.ip_range_white_list_file: "%kernel.root_dir%/config/white_list_ip_range.yml"

    # Core plugin API descriptors
    claroline.api.sample.dir:      "%claroline.param.vendor_directory%/claroline/distribution/main/core/Resources/samples"
    claroline.api.core_schema.dir: "%claroline.param.vendor_directory%/claroline/distribution/main/core/Resources/schema"
