claro_security_login_check:
    path: /login_check
    options: { expose: true }

claro_security_logout:
    path: /logout

claro_oauth_authorize:
    resource: "@ClarolineCoreBundle/Controller/OauthController.php"
    type: annotation

claro_index:
    resource: "@ClarolineCoreBundle/Controller/HomeController.php"
    type: annotation

claro_redirect:
    resource: "@ClarolineCoreBundle/Controller/RedirectController.php"
    type: annotation

claro_locale:
    resource: "@ClarolineCoreBundle/Controller/LocaleController.php"
    type: annotation

claro_theme:
    resource: "@ClarolineCoreBundle/Controller/Administration/ThemeController.php"
    type: annotation

claro_content_typeerror:
    path: /content/typeerror
    options: { expose: true }
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:typeerror.html.twig'

claro_content_confirm:
    path: /content/confirm
    options: { expose: true }
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:confirm.html.twig'

claro_content_link:
    path: /content/link
    options: { expose: true }
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:link.html.twig'

claro_authentication:
    resource: "@ClarolineCoreBundle/Controller/AuthenticationController.php"
    type: annotation

claro_log:
    resource: "@ClarolineCoreBundle/Controller/Log/LogController.php"
    prefix: log
    type: annotation

claro_log_workspace:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceLogController.php"
    prefix: workspaces
    type: annotation

# old
claro_profile:
    resource: "@ClarolineCoreBundle/Controller/ProfileController.php"
    prefix: profile
    type: annotation

# new
claro_user_profile:
    resource: "@ClarolineCoreBundle/Controller/User/ProfileController.php"
    type: annotation
    options: { expose: true }

claro_user_registration:
    resource: "@ClarolineCoreBundle/Controller/User/RegistrationController.php"
    type: annotation
    options: { expose: true }

claro_user_tracking:
    resource: "@ClarolineCoreBundle/Controller/User/TrackingController.php"
    type: annotation
    options: { expose: true }

claro_desktop:
    resource: "@ClarolineCoreBundle/Controller/DesktopController.php"
    type: annotation

claro_desktop_tool_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/DesktopParametersController.php"
    prefix: desktop/tool/properties
    type: annotation

claro_workspace:
    resource: "@ClarolineCoreBundle/Controller/WorkspaceController.php"
    prefix: workspaces
    type: annotation

claro_workspace_tag:
    resource: "@ClarolineCoreBundle/Controller/WorkspaceTagController.php"
    prefix: workspaces
    type: annotation

claro_workspace_tool_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceParametersController.php"
    prefix: workspaces/tool/properties
    type: annotation

claro_workspace_tool_tools_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceToolsParametersController.php"
    prefix: workspaces/tool/properties
    type: annotation

claro_workspace_tool_home:
    resource: "@ClarolineCoreBundle/Controller/Tool/HomeController.php"
    prefix: workspaces/tool/home
    type: annotation

claro_workspace_dashboard:
    prefix: workspace/dashboard
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceDashboardController.php"
    type: annotation

claro_admin:
    resource: "@ClarolineCoreBundle/Controller/AdministrationController.php"
    prefix: admin
    type: annotation

claro_admin_desktop_configuration:
    resource: "@ClarolineCoreBundle/Controller/Administration/DesktopConfigurationController.php"
    prefix: admin
    type: annotation

claro_admin_home_tab:
    resource: "@ClarolineCoreBundle/Controller/Administration/HomeTabController.php"
    prefix: admin
    type: annotation

claro_admin_portal_config:
    resource: "@ClarolineCoreBundle/Controller/Administration/PortalConfigurationController.php"
    prefix: admin/portal
    type: annotation

claro_resources_node_api:
    resource: "@ClarolineCoreBundle/Controller/API/Resource/ResourceNodeController.php"
    prefix: api
    type: annotation
    options:
        expose: true

# todo : remove me
claro_resource_old:
    resource: "@ClarolineCoreBundle/Controller/ResourceOldController.php"
    prefix: /old
    type: annotation

claro_resource:
    resource: "@ClarolineCoreBundle/Controller/ResourceController.php"
    type: annotation

claro_widget:
    resource: "@ClarolineCoreBundle/Controller/Widget"
    prefix: widget
    type: annotation

claro_activity:
    resource: "@ClarolineCoreBundle/Controller/ActivityController.php"
    prefix: activity/
    type: annotation

claro_activity_remove_resource_confirm:
    path: /activity/remove
    options: { expose: true }
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Activity:remove.html.twig'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

claro_file:
    resource: "@ClarolineCoreBundle/Controller/FileController.php"
    type: annotation
    prefix: file

claro_user:
    resource: "@ClarolineCoreBundle/Controller/UserController.php"
    type: annotation
    prefix: user

claro_admin_parameters:
    prefix: admin/parameters
    resource: "@ClarolineCoreBundle/Controller/Administration/ParametersController.php"
    type: annotation

claro_admin_logs:
    prefix: admin/logs
    resource: "@ClarolineCoreBundle/Controller/Administration/LogsController.php"
    type: annotation

claro_admin_analytics:
    prefix: admin/analytics
    resource: "@ClarolineCoreBundle/Controller/Administration/AnalyticsController.php"
    type: annotation

claro_admin_workspace_registration:
    prefix: admin/workspace/registration
    resource: "@ClarolineCoreBundle/Controller/Administration/WorkspaceRegistrationController.php"
    type: annotation

claro_admin_oauth:
    resource: "@ClarolineCoreBundle/Controller/Administration/OauthController.php"
    prefix: admin/oauth
    type: annotation

claro_admin_i18n:
    resource: "@ClarolineCoreBundle/Controller/Administration/InternationalizationController.php"
    prefix: admin/i18n
    type: annotation

claro_admin_plugin:
    resource: "@ClarolineCoreBundle/Controller/Administration/PluginController.php"
    prefix: admin/plugins
    type: annotation

claro_api:
    resource: "@ClarolineCoreBundle/Controller/API/User/ApiController.php"
    type: rest
    prefix: api
    defaults: {_format: json}
    options:
        expose: true

claro_plugin_api:
    resource: "@ClarolineCoreBundle/Controller/API/Admin/PluginController.php"
    prefix: api
    type: rest
    defaults: {_format: json}
    options:
        expose: true

claro_portal:
    resource: "@ClarolineCoreBundle/Controller/PortalController.php"
    prefix: portal
    type: annotation

claro_admin_widget:
    prefix: admin/widget
    resource: "@ClarolineCoreBundle/Controller/Administration/WidgetController.php"
    type: annotation

claro_desktop_home_api:
    resource: "@ClarolineCoreBundle/Controller/API/Desktop/DesktopHomeController.php"
    type: annotation

claro_workspace_home_api:
    resource: "@ClarolineCoreBundle/Controller/API/Workspace/WorkspaceHomeController.php"
    type: annotation

claro_client:
    resource: "@ClarolineCoreBundle/Controller/API/Admin/ClientController.php"
    type: annotation
    prefix: api

claro_admin_resource_icons:
    resource: "@ClarolineCoreBundle/Controller/Administration/IconController.php"
    prefix: admin/parameters/appearance/icon
    type: annotation

claro_new_api:
    resource: "@ClarolineCoreBundle/Controller/APINew/"
    prefix: apiv2
    type: api
    options:
        expose: true
