claro_security_login_check:
    pattern: /login_check
    options: { expose: true }

claro_security_logout:
    pattern: /logout

claro_index:
    resource: "@ClarolineCoreBundle/Controller/HomeController.php"
    type: annotation

claro_theme:
    resource: "@ClarolineCoreBundle/Controller/ThemeController.php"
    prefix: /admin/theme
    type: annotation

claro_theme_error:
    pattern: /admin/theme/error
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Theme:error.html.twig'

claro_theme_confirm:
    pattern: /admin/theme/confirm
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Theme:confirm.html.twig'

claro_content_error:
    pattern: /content/error
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:ajaxerror.html.twig'

claro_content_typeerror:
    pattern: /content/typeerror
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:typeerror.html.twig'

claro_content_confirm:
    pattern: /content/confirm
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:confirm.html.twig'

claro_content_link:
    pattern: /content/link
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'ClarolineCoreBundle:Home:link.html.twig'


claro_authentication:
    resource: "@ClarolineCoreBundle/Controller/AuthenticationController.php"
    type: annotation

claro_log:
    resource: "@ClarolineCoreBundle/Controller/Log/LogController.php"
    prefix: log
    type: annotation

claro_log_admin:
    resource: "@ClarolineCoreBundle/Controller/Log/AdministrationController.php"
    prefix: admin
    type: annotation

claro_log_workspace:
    resource: "@ClarolineCoreBundle/Controller/Log/Tool/WorkspaceController.php"
    prefix: workspaces
    type: annotation

claro_profile:
    resource: "@ClarolineCoreBundle/Controller/ProfileController.php"
    prefix: profile
    type: annotation

claro_registration:
    resource: "@ClarolineCoreBundle/Controller/RegistrationController.php"
    type: annotation
    prefix: register

claro_desktop:
    resource: "@ClarolineCoreBundle/Controller/DesktopController.php"
    prefix: desktop
    type: annotation

claro_desktop_tool_agenda:
    resource: "@ClarolineCoreBundle/Controller/Tool/DesktopAgendaController.php"
    prefix: desktop/tool/agenda
    type: annotation

claro_desktop_tool_home:
    resource: "@ClarolineCoreBundle/Controller/Tool/HomeController.php"
    prefix: tool/home
    type: annotation

claro_desktop_tool_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/DesktopParametersController.php"
    prefix: desktop/tool/properties
    type: annotation

claro_workspace:
    resource: "@ClarolineCoreBundle/Controller/WorkspaceController.php"
    prefix: workspaces
    type: annotation

claro_workspace_tag:
    resource: "@ClarolineCoreBundle/Controller/WorkspaceTagController.php"
    prefix: workspaces
    type: annotation

claro_workspace_tool_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceParametersController.php"
    prefix: workspaces/tool/properties
    type: annotation

claro_workspace_tool_tools_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceToolsParametersController.php"
    prefix: workspaces/tool/properties
    type: annotation

claro_workspace_tool_resources_properties:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceResourceParametersController.php"
    prefix: workspaces/tool/properties
    type: annotation

claro_workspace_tool_agenda:
    resource: "@ClarolineCoreBundle/Controller/Tool/WorkspaceAgendaController.php"
    prefix: workspaces/tool/agenda
    type: annotation

claro_workspace_roles:
    resource: "@ClarolineCoreBundle/Controller/Tool/RolesController.php"
    prefix: workspaces/tools/roles/
    type: annotation

claro_admin:
    resource: "@ClarolineCoreBundle/Controller/AdministrationController.php"
    prefix: admin
    type: annotation

claro_admin_home_tab:
    resource: "@ClarolineCoreBundle/Controller/AdministrationHomeTabController.php"
    prefix: admin
    type: annotation

claro_admin_widget:
    resource: "@ClarolineCoreBundle/Controller/AdministrationWidgetController.php"
    prefix: admin
    type: annotation

claro_admin_tool:
    resource: "@ClarolineCoreBundle/Controller/Tool/AdministrationToolController.php"
    prefix: admin
    type: annotation

claro_resource:
    resource: "@ClarolineCoreBundle/Controller/ResourceController.php"
    prefix: resource
    type: annotation

claro_resource_parameters:
    resource: "@ClarolineCoreBundle/Controller/ResourcePropertiesController.php"
    prefix: resource
    type: annotation

claro_resource_rights:
    resource: "@ClarolineCoreBundle/Controller/ResourceRightsController.php"
    prefix: resource
    type: annotation
claro_resource_type:
    resource: "@ClarolineCoreBundle/Controller/ResourceTypeController.php"
    prefix: resource
    type: annotation

claro_tool_resoure_manager:
    resource: "@ClarolineCoreBundle/Controller/Tool/ResourceManagerController.php"
    prefix: resource
    type: annotation

claro_text:
    resource: "@ClarolineCoreBundle/Controller/TextController.php"
    prefix: text
    type: annotation

claro_simple_text_widget:
    resource: "@ClarolineCoreBundle/Controller/Widget/SimpleTextController.php"
    prefix: widget
    type: annotation

claro_mail:
    resource: "@ClarolineCoreBundle/Controller/MailController.php"
    prefix: mail
    type: annotation

claro_message:
    resource: "@ClarolineCoreBundle/Controller/MessageController.php"
    prefix: message
    type: annotation

claro_activity:
    resource: "@ClarolineCoreBundle/Controller/ActivityController.php"
    prefix: activity
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

claro_install:
    resource: "@ClarolineCoreBundle/Controller/InstallController.php"
    type: annotation
    prefix: install

claro_file:
    resource: "@ClarolineCoreBundle/Controller/FileController.php"
    type: annotation
    prefix: file

idci_exporter:
    resource: "../../vendor/idci/exporter-bundle/IDCI/Bundle/ExporterBundle/Controller"
    type:     annotation
# app/config/routing.yml
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

# Badge routes
claro_badge_admin:
    resource: "@ClarolineCoreBundle/Controller/Badge/AdminController.php"
    type:     annotation

claro_badge_front:
    resource: "@ClarolineCoreBundle/Controller/Badge/FrontController.php"
    type:     annotation

claro_badge_profil:
    resource: "@ClarolineCoreBundle/Controller/Badge/ProfileController.php"
    type:     annotation
