# This file contains only services that cannot be defined using annotations.

services:
    # service definition is conditional (parameter depend on the environment)
    claroline.config.platform_config_handler:
        class: %claroline.param.platform_config_handler_class%
        arguments:
            - %claroline.param.platform_options_files%
    # array injection with annotations is not supported
    claroline.plugin.validator:
        class: Claroline\CoreBundle\Library\Installation\Plugin\Validator
        arguments:
            - routing: "@claroline.plugin.routing_checker"
              config: "@claroline.plugin.config_checker"
    # vendor classes used as service arguments
    claroline.symfony_yaml:
        class: Symfony\Component\Yaml\Yaml
        public: false

    claroline.common.theme_service:
        class: Claroline\CoreBundle\Library\Themes\ThemeService
        arguments:
            - "@service_container"
