UJM\ExoBundle\Entity\InteractionQCM:
    properties:
        scoreRightResponse:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMGlobalMark: ~

        scoreFalseResponse:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMGlobalMark: ~
            
UJM\ExoBundle\Entity\Hint:
    properties:
        penalty:
            - UJM\ExoBundle\Validator\Constraints\isValidMark: ~
            
UJM\ExoBundle\Entity\Choice:
    properties:
        weight:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMMark: ~            