language: php

php:
  - "5.5"

env:
  - DB=mysql

mysql:
  adapter: mysql2
  database: claroline_test
  username: root
  encoding: utf8

before_script:
  # keep a list of files impacted by the PR
  - git diff-tree --no-commit-id --diff-filter=ACM --name-only -r ${TRAVIS_COMMIT_RANGE/.../ } > git_diff_files.txt

  # leave build/repo dir
  - cd ../..

  # increase php memory size (required for composer)
  - echo "memory_limit=3072M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # disable xdebug
  - phpenv config-rm xdebug.ini

  # get node >=5.6
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 5
  - nvm use --delete-prefix 5

  # get and configure claroline platform
  - curl -L https://github.com/claroline/Claroline/archive/monolithic-build.tar.gz | tar xzv
  - cd Claroline-monolithic-build
  - php scripts/configure.php --default

  # override platform composer.json with build/repo local reference
  - mkdir -p travis/local/pkg && mv ../$TRAVIS_REPO_SLUG/* ../$TRAVIS_REPO_SLUG/.[!.]* travis/local/pkg
  - rm -rf travis/local/pkg/.git
  - php travis/local/pkg/main/dev/Resources/travis/pre-composer.php claroline/distribution travis/local/pkg

  # fetch dependencies and build
  - composer update --prefer-source
  - npm install
  - npm run bower
  - composer build
  - php app/console doctrine:database:create --env=test
  - php app/console claroline:init_test_schema --env=test

script:
  - bin/php-cs-fixer fix --dry-run --diff --config-file=vendor/claroline/distribution/main/dev/Resources/travis/php-cs.php
  - SYMFONY_DEPRECATIONS_HELPER=weak bin/phpunit -c vendor/claroline/distribution
