jobs:
  include:
    - php: 7.4
      env: NODE_RELEASE=14
      dist: focal # with mysql 8.0

language: php

env:
  - DB=mysql

services:
  - xvfb
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install ${NODE_RELEASE}
  # prepare execution of chromium in js tests
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - export ENV=PROD
  - export APP_ENV=test
  - export APP_DEBUG=0

before_script:
  # add swap
  - sudo swapon -s
  - sudo fallocate -l 8G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo swapon -s

  - cd claroline
  - composer validate
  - php bin/configure --default
  - COMPOSER_MEMORY_LIMIT=-1 composer install --optimize-autoloader
  - npm install
  - npm run webpack
  - php bin/console claroline:install --env=test -vvv
  - export SYMFONY_DEPRECATIONS_HELPER=weak

script:
  - ./vendor/bin/simple-phpunit --dont-report-useless-tests -c vendor/claroline/distribution
  # TODO : enable when JS test suite is fixed
  # - node_modules/.bin/karma start vendor/claroline/distribution/karma.conf.js --single-run
