language: php

php:
  - "7.2"

env:
  - DB=mysql

services:
  - xvfb

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 6.12
  # prepare execution of chromium in js tests
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  # add swap
  - sudo swapon -s
  - sudo fallocate -l 4G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - sudo swapon -s
  
  - composer validate
  - php scripts/configure.php --default
  - composer sync-dev
  - php app/console claroline:install --env=test
  - export SYMFONY_DEPRECATIONS_HELPER=weak

script:
  - vendor/bin/phpunit -c vendor/claroline/distribution
  # TODO : enable when JS test suite is fixed
  # - node_modules/.bin/karma start vendor/claroline/distribution/karma.conf.js --single-run
