language: php

php:
  - "5.5"

env:
  - DB=mysql

mysql:
  adapter: mysql2
  database: claroline_test_travis
  username: travis
  encoding: utf8

before_script:
  - cd ../..
  - ROOT_DIR=`pwd`
  - curl -O https://raw.githubusercontent.com/claroline/DevBundle/master/Resources/travis/pre-composer.php
  - php pre-composer.php
  - BUNDLE_DIR=`cat bundle_dir.txt`
  - cd $BUNDLE_DIR
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - COMPOSER=composer_travis.json composer update --prefer-source
  - cd $ROOT_DIR
  - cp -R vendor/claroline/dev-bundle/Claroline/DevBundle/Resources/travis/app/* app
  - php app/register-bundle.php $BUNDLE_DIR
  - rm -rf app/cache/*
  - php app/init-schema.php

script: vendor/bin/phpunit -c "${BUNDLE_DIR}/phpunit_travis.xml"

sudo: false