language: php

php:
  - "5.5"

env:
  - DB=mysql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 5

before_script:
  - php scripts/configure.php --default
  - composer sync-dev
  - php app/console claroline:install --env=test
  - export SYMFONY_DEPRECATIONS_HELPER=weak

script:
  - vendor/bin/phpunit -c vendor/claroline/distribution
  - node_modules/.bin/karma start vendor/claroline/distribution/karma.conf.js --single-run --browsers PhantomJS
