services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true

    Claroline\BigBlueButtonBundle\Listener\Resource\BBBListener:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\BigBlueButtonBundle\Manager\BBBManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
        tags:
            - { name: kernel.event_listener, event: resource.claroline_big_blue_button.load, method: onLoad }
            - { name: kernel.event_listener, event: resource.claroline_big_blue_button.delete, method: onDelete }
            - { name: kernel.event_listener, event: resource.claroline_big_blue_button.soft_delete, method: onSoftDelete }
