ujm_exercise_docimology:
     pattern:  /docimology/{exerciseId}/{nbPapers}
     defaults: { _controller: "UJMExoBundle:Exercise:docimology" }

ujm_exercise_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UJMExoBundle:Exercise:edit" }

ujm_exercise_import_question:
    pattern: /{exoID}/import/{pageGoNow}/{maxPage}/{nbItem}
    defaults: { _controller: UJMExoBundle:Exercise:importQuestion, pageGoNow: 1, maxPage: 10, nbItem: 1 }

ujm_exercise_questions:
    pattern:  /{id}/questions/{pageNow}/{categoryToFind}/{titleToFind}
    defaults: { _controller: UJMExoBundle:Exercise:showQuestions, pageNow: 0, categoryToFind: z, titleToFind: z }

ujm_exercise_question_delete:
    pattern:  /{exoID}/{qid}/delete/{pageNow}/{maxPage}/{nbItem}/{lastPage}
    defaults: { _controller: UJMExoBundle:Exercise:deleteQuestion, pageNow: 1, maxPage: 10, nbItem: 1, lastPage: 1 }
    requirements: { _method: post }

ujm_exercise_update:
    pattern:  /{id}/update
    defaults: { _controller: "UJMExoBundle:Exercise:update" }
    requirements: { _method: post }

ujm_exercise_validate_import:
    pattern: /{exoID}/{qid}/import/{pageGoNow}
    defaults: { _controller: UJMExoBundle:Exercise:importValidate, pageGoNow: 1 }

ujm_exercise_validate_import_shared:
    pattern: /import/shared/{exoID}/{qid}/{pageGoNow}
    defaults: { _controller: UJMExoBundle:Exercise:importValidateShared, pageGoNow: 1 }