services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    # Authenticators
    Claroline\AuthenticationBundle\Security\Authentication\Authenticator:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@security.token_storage'
            - '@security.encoder_factory'

    Claroline\AuthenticationBundle\Security\Authentication\IpAuthenticator:
        calls:
            - method: inject
              arguments:
                  - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
                  - '@claroline.manager.ip_white_list_manager'

    Claroline\AuthenticationBundle\Security\Authentication\ApiTokenAuthenticator:
        calls:
            - method: inject
              arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'

    # OAuth
    Claroline\AuthenticationBundle\Security\Oauth\Hwi\ResourceOwnerFactory:
        arguments:
            - '@Claroline\AuthenticationBundle\Manager\OauthManager'
            - '@security.http_utils'
            - '@session'

    Claroline\AuthenticationBundle\Security\Oauth\FailureHandler:
        arguments:
            - '@router'
            - '@translator'

    Claroline\AuthenticationBundle\Security\Oauth\LogoutSuccessHandler:
        arguments:
            - '@session'
            - '@router'
            - '@Claroline\AuthenticationBundle\Security\Oauth\Hwi\ResourceOwnerFactory'

    Claroline\AuthenticationBundle\Security\Oauth\OauthUserProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
