services:
    _defaults:
        tags: [ 'claroline.platform.updater' ]

    Claroline\CommunityBundle\Installation\Updater\Updater130500:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CommunityBundle\Installation\Updater\Updater130700:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
