imports:
    - { resource: doctrine_dev.yml }

doctrine:
    dbal:
        driver:   '%test_database_driver%'
        host:     '%test_database_host%'
        dbname:   '%test_database_name%'
        user:     '%test_database_user%'
        password: '%test_database_password%'
