services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\Controller\AbstractCrudController:
            calls:
              - method: setFinder
                arguments:
                  - '@Claroline\AppBundle\API\FinderProvider'
              - method: setSerializer
                arguments:
                  - '@Claroline\AppBundle\API\SerializerProvider'
              - method: setCrud
                arguments:
                  - '@Claroline\AppBundle\API\Crud'
              - method: setObjectManager
                arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'
              - method: setRouterFinder
                arguments:
                  - '@Claroline\AppBundle\Routing\Finder'
              - method: setRouterDocumentator
                arguments:
                  - '@Claroline\AppBundle\Routing\Documentator'
              - method: setContainer
                arguments:
                  - '@service_container'

    Claroline\AppBundle\Controller\Platform\ClientController:
        arguments:
          - '@security.token_storage'
          - '@twig'
          - '@Claroline\AppBundle\Event\StrictDispatcher'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '@Claroline\AppBundle\Manager\SecurityManager'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@Claroline\CoreBundle\API\Serializer\Platform\ClientSerializer'

    Claroline\AppBundle\Controller\Platform\LocaleController:
        arguments:
          - '@claroline.manager.locale_manager'
          - '@security.token_storage'
