services:
  user_repository:
    class:           Claroline\CoreBundle\Repository\UserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\User

  message_repository:
    class:           Claroline\CoreBundle\Repository\MessageRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Message

  resource_type_repository:
    class:           Claroline\CoreBundle\Repository\ResourceTypeRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\ResourceType

  resource_rights_repository:
    class:           Claroline\CoreBundle\Repository\ResourceRightsRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\ResourceRights

  resource_repository:
    class:           Claroline\CoreBundle\Repository\AbstractResourceRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\AbstractResource

  role_repository:
    class:           Claroline\CoreBundle\Repository\RoleRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Role

  shortcut_repository:
    class:           Claroline\CoreBundle\Repository\ShortcutRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Resource\ResourceShortcut

  workspace_tag_repository:
    class:           Claroline\CoreBundle\Repository\WorkspaceTagRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Workspace\WorkspaceTag

  rel_workspace_tag_repository:
    class:           Claroline\CoreBundle\Repository\RelWorkspaceTagRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Workspace\RelWorkspaceTag

  workspace_tag_hierarchy_repository:
    class:           Claroline\CoreBundle\Repository\WorkspaceTagHierarchyRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\Workspace\WorkspaceTagHierarchy

  claroline.repository.user_message_repository:
    class:           Claroline\CoreBundle\Repository\UserMessageRepository
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
      - Claroline\CoreBundle\Entity\UserMessage
