services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\Controller\AbstractCrudController:
            calls:
              - method: setFinder
                arguments:
                  - '@Claroline\AppBundle\API\FinderProvider'
              - method: setSerializer
                arguments:
                  - '@Claroline\AppBundle\API\SerializerProvider'
              - method: setCrud
                arguments:
                  - '@Claroline\AppBundle\API\Crud'
              - method: setObjectManager
                arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'
              - method: setRouterFinder
                arguments:
                  - '@Claroline\AppBundle\Routing\Finder'
              - method: setRouterDocumentator
                arguments:
                  - '@Claroline\AppBundle\Routing\Documentator'
              - method: setContainer
                arguments:
                  - '@service_container'
                  
        Claroline\AppBundle\Controller\AbstractSecurityController:
            calls:
              - method: setObjectManager
                arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'
              - method: setAuthorizationChecker
                arguments:
                  - '@security.authorization_checker'

    Claroline\CoreBundle\Controller\LegacyController:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\CoreBundle\Library\RoutingHelper'

    Claroline\CoreBundle\Controller\APINew\Cryptography\ApiTokenController:
        arguments:
          - '@security.token_storage'

    Claroline\CoreBundle\Controller\APINew\Log\LogConnectController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@claroline.manager.log_connect'
          - '@claroline.manager.tool_manager'

    Claroline\CoreBundle\Controller\APINew\Platform\PluginController:
        tags: [security.secure_service]
        arguments:
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Controller\APINew\Resource\Types\DirectoryController: ~

    Claroline\CoreBundle\Controller\APINew\Resource\Types\FileController: ~

    Claroline\CoreBundle\Controller\APINew\Resource\Types\TextController: ~

    Claroline\CoreBundle\Controller\APINew\Resource\ResourceCommentController: ~

    Claroline\CoreBundle\Controller\APINew\Resource\ResourceNodeController:
        arguments:
          - '@claroline.manager.resource_action'
          - '@claroline.manager.resource_manager'
          - '@claroline.manager.rights_manager'
          - '@claroline.manager.log_connect'
          - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'

    Claroline\CoreBundle\Controller\APINew\Template\TemplateController:
        arguments:
          - '@security.authorization_checker'
          - '@claroline.manager.template_manager'
          - '@claroline.manager.tool_manager'

    Claroline\CoreBundle\Controller\APINew\Template\TemplateTypeController: ~

    Claroline\CoreBundle\Controller\APINew\Tool\HomeController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\AppBundle\API\Crud'
          - '@claroline.manager.lock_manager'
          - '@Claroline\CoreBundle\API\Serializer\Widget\HomeTabSerializer'

    Claroline\CoreBundle\Controller\APINew\Tool\ToolController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@event_dispatcher'
          - '@Claroline\AppBundle\API\Crud'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
          - '@Claroline\CoreBundle\Manager\Tool\ToolRightsManager'
          - '@Claroline\CoreBundle\Manager\Tool\ToolMaskDecoderManager'
          - '@Claroline\CoreBundle\Manager\LogConnectManager'

    Claroline\CoreBundle\Controller\APINew\User\GroupController:
        arguments:
          - '@security.token_storage'
          - '@security.authorization_checker'

    Claroline\CoreBundle\Controller\APINew\User\LocationController: ~

    Claroline\CoreBundle\Controller\APINew\User\OrganizationController: ~

    Claroline\CoreBundle\Controller\APINew\User\ProfileController:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\Crud'
          - '@Claroline\CoreBundle\API\Serializer\User\ProfileSerializer'

    Claroline\CoreBundle\Controller\APINew\User\RoleController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\CoreBundle\Manager\LogManager'

    Claroline\CoreBundle\Controller\APINew\User\UserController:
        arguments:
          - '@security.token_storage'
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\Event\StrictDispatcher'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '@claroline.manager.user_manager'
          - '@claroline.manager.mail_manager'
          - '@claroline.manager.registration_manager'

    Claroline\CoreBundle\Controller\APINew\Workspace\EvaluationController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\Controller\APINew\Workspace\RegistrationController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\AppBundle\API\Crud'
          - '@claroline.manager.workspace_manager'
          - '@claroline.manager.workspace_user_queue_manager'

    Claroline\CoreBundle\Controller\APINew\Workspace\RequirementsController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\CoreBundle\Manager\Workspace\EvaluationManager'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\Controller\APINew\Workspace\WorkspaceController:
        arguments:
          - '@security.token_storage'
          - '@security.authorization_checker'
          - '@claroline.manager.resource_manager'
          - '@translator'
          - '@claroline.manager.role_manager'
          - '@claroline.manager.tool_manager'
          - '@claroline.manager.workspace_manager'
          - '@Claroline\CoreBundle\Library\Security\Utilities'
          - '@Claroline\CoreBundle\Library\Utilities\FileUtilities'
          - '@claroline.manager.workspace.transfer'
          - '@claroline.manager.temp_file'
          - '%claroline.param.workspace_log_dir%'
          - '@claroline.manager.log_connect'

    Claroline\CoreBundle\Controller\APINew\Platform\ConnectionMessageController:
        arguments:
          - '@claroline.manager.connection_message_manager'

    Claroline\CoreBundle\Controller\APINew\DataSourceController:
        arguments:
          - '@Claroline\AppBundle\Event\StrictDispatcher'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.data_source'

    Claroline\CoreBundle\Controller\APINew\SavedSearchController:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\AppBundle\API\Crud'

    Claroline\CoreBundle\Controller\APINew\FileController:
        arguments:
          - '@Claroline\AppBundle\Event\StrictDispatcher'

    Claroline\CoreBundle\Controller\APINew\LoggerController:
        arguments:
          - '%claroline.param.log_dir%'

    Claroline\CoreBundle\Controller\APINew\ObjectLockController:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.lock_manager'

    Claroline\CoreBundle\Controller\APINew\Platform\ParametersController:
        arguments:
          - '@Claroline\AppBundle\Event\StrictDispatcher'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '@Claroline\AnalyticsBundle\Manager\AnalyticsManager'
          - '@Claroline\CoreBundle\Manager\VersionManager'
          - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'

    Claroline\CoreBundle\Controller\APINew\Platform\ScheduledTaskController: ~

    Claroline\CoreBundle\Controller\APINew\SwaggerController:
        arguments:
          - '@Claroline\AppBundle\Routing\Finder'
          - '@Claroline\AppBundle\Routing\Documentator'
          - '@Claroline\AppBundle\API\SchemaProvider'
          - '@Claroline\AppBundle\Manager\PlatformManager'
          - '%kernel.root_dir%'

    Claroline\CoreBundle\Controller\APINew\TransferController:
        arguments:
          - '@Claroline\AppBundle\API\TransferProvider'
          - '%claroline.api.core_schema.dir%'

    Claroline\CoreBundle\Controller\APINew\WidgetController:
        arguments:
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.widget_manager'
          - '@Claroline\CoreBundle\Manager\DataSourceManager'

    Claroline\CoreBundle\Controller\Administration\ArchiveController:
        arguments:
          - '%claroline.param.archive_directory%'
        tags: ['security.secure_service']

    Claroline\CoreBundle\Controller\User\RegistrationController:
        arguments:
          - '@security.token_storage'
          - '@session'
          - '@translator'
          - '@Claroline\CoreBundle\API\Serializer\User\ProfileSerializer'
          - '@claroline.manager.user_manager'
          - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'
          - '@Claroline\CoreBundle\Library\RoutingHelper'

    Claroline\CoreBundle\Controller\AdministrationController:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'
          - '@event_dispatcher'
          - '@claroline.manager.tool_manager'

    Claroline\CoreBundle\Controller\AuthenticationController:
        tags: ['security.secure_service']
        arguments:
          - '@request_stack'
          - '@claroline.manager.user_manager'
          - '@security.encoder_factory'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@translator'
          - '@Claroline\AuthenticationBundle\Security\Authentication\Authenticator'
          - '@claroline.manager.mail_manager'
          - '@router'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '@Claroline\AppBundle\Event\StrictDispatcher'

    Claroline\CoreBundle\Controller\DesktopController:
        tags: ['security.secure_service']
        arguments:
          - '@security.authorization_checker'
          - '@event_dispatcher'
          - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.tool_manager'

    Claroline\CoreBundle\Controller\FileController:
        arguments:
          - '@session'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '%claroline.param.files_directory%'
          - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
          - '@claroline.manager.resource_manager'
          - '@claroline.manager.role_manager'
          - '@Claroline\CoreBundle\Library\Utilities\FileUtilities'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@security.token_storage'
          - '@security.authorization_checker'

    Claroline\CoreBundle\Controller\ResourceController:
        arguments:
          - '@security.token_storage'
          - '@templating'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\CoreBundle\Library\Security\Utilities'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.resource_manager'
          - '@claroline.manager.resource_action'
          - '@claroline.manager.resource_restrictions'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@security.authorization_checker'

    Claroline\CoreBundle\Controller\SearchController:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\Controller\WorkspaceController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@event_dispatcher'
          - '@security.token_storage'
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@claroline.manager.tool_manager'
          - '@translator'
          - '@claroline.manager.workspace_manager'
          - '@claroline.manager.workspace_restrictions'
          - '@Claroline\CoreBundle\Manager\Workspace\EvaluationManager'

    Claroline\CoreBundle\Controller\APINew\Icon\IconSetController: ~

    Claroline\CoreBundle\Controller\APINew\Icon\IconItemController:
        arguments:
          - '@security.authorization_checker'
          - '@claroline.manager.icon_set_manager'
          - '@claroline.manager.tool_manager'
