services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Claroline\CoreBundle\Library\Configuration\PlatformDefaults:
        tags: ['claroline.configuration']

    Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler:
        arguments:
            - '%claroline.param.platform_options%'

    Claroline\CoreBundle\Library\Configuration\LegacyParametersMapping:
        tags: ['claroline.configuration.mapping.legacy']

    Claroline\CoreBundle\Library\Installation\Refresher:
        arguments:
            - '@service_container'

    Claroline\CoreBundle\Library\Installation\OperationExecutor:
        arguments:
            - '@kernel'
            - '@claroline.installation.manager'
            - '@Claroline\CoreBundle\Library\Installation\Plugin\Installer'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.manager.version_manager'
        calls:
            - setLogger: ['@logger']

    Claroline\CoreBundle\Library\Installation\Plugin\RoutingChecker:
        arguments:
            - '@claroline.symfony_yaml'

    Claroline\CoreBundle\Library\Installation\Plugin\Recorder:
        arguments:
            - '@Claroline\CoreBundle\Library\Installation\Plugin\DatabaseWriter'
            - '@claroline.plugin.validator'

    Claroline\CoreBundle\Library\Installation\Plugin\Loader: ~

    Claroline\CoreBundle\Library\Installation\Plugin\Installer:
        arguments:
            - '@claroline.plugin.validator'
            - '@Claroline\CoreBundle\Library\Installation\Plugin\Recorder'
            - '@claroline.installation.manager'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.manager.plugin_manager'
            - '@translator'
            - '@claroline.manager.version_manager'
        calls:
            - setLogger: [ '@logger' ]

    Claroline\CoreBundle\Library\Installation\Plugin\DatabaseWriter:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.manager.mask_manager'
            - '@filesystem'
            - '@kernel'
            - '@Claroline\CoreBundle\Manager\Tool\ToolManager'
            - '@Claroline\CoreBundle\Manager\Tool\ToolMaskDecoderManager'
            - '@claroline.manager.icon_set_manager'
        calls:
            - setLogger: [ '@logger' ]

    Claroline\CoreBundle\Library\Installation\Plugin\ConfigurationChecker:
        arguments:
            - '@claroline.symfony_yaml'
            - '@doctrine.orm.entity_manager'

    Claroline\CoreBundle\Library\Installation\PlatformInstaller:
        arguments:
            - '@Claroline\CoreBundle\Library\Installation\OperationExecutor'
            - '@claroline.installation.manager'
            - '@Claroline\CoreBundle\Library\Installation\Plugin\Installer'
            - '@Claroline\CoreBundle\Library\Installation\Refresher'
            - '@kernel'
            - '@service_container'
        calls:
            - setLogger: [ '@logger' ]

    Claroline\CoreBundle\Library\Mailing\TransportFactory:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'

    Claroline\CoreBundle\Library\Mailing\Mailer:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '%kernel.project_dir%/app'

    Claroline\CoreBundle\Library\Mailing\Client\SwiftMailer:
        tags: ['claroline.mailing']
        arguments:
            - '@mailer'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'

    Claroline\CoreBundle\Library\Mailing\Client\Postal:
        tags: ['claroline.mailing']
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'

    Claroline\CoreBundle\Library\Utilities\FileUtilities:
        arguments:
            - '%claroline.param.files_directory%'
            - '@filesystem'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '%claroline.param.public_files_directory%'
            - '@security.token_storage'

    Claroline\CoreBundle\Library\Utilities\MimeTypeGuesser: ~

    Claroline\CoreBundle\Library\Utilities\ClaroUtilities:
        arguments:
            - '@service_container'

    Claroline\CoreBundle\Library\Session\SessionStorageOptionsFactory:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '%session.storage.options%'

    Claroline\CoreBundle\Library\Session\SessionHandlerFactory:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '%session.save_path%'
            - '%database_user%'
            - '%database_password%'
            - '%database_name%'

    Claroline\CoreBundle\Library\Session\DatabaseSessionValidator: ~

    Claroline\CoreBundle\Library\Security\Utilities: ~

    Claroline\CoreBundle\Library\RoutingHelper:
       arguments:
          - '@router'
