services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true
        tags: [claroline.transfer.action]

    _instanceof:
        Claroline\AppBundle\API\Transfer\Action\AbstractCreateAction:
            tags: [claroline.transfer.action]
            calls:
                - method: setCrud
                  arguments:
                     - '@Claroline\AppBundle\API\Crud'

        Claroline\AppBundle\API\Transfer\Action\AbstractCreateOrUpdateAction:
            tags: [claroline.transfer.action]
            calls:
                - method: setCrud
                  arguments:
                     - '@Claroline\AppBundle\API\Crud'
                - method: setSerializer
                  arguments:
                     - '@Claroline\AppBundle\API\SerializerProvider'
                - method: setTransfer
                  arguments:
                     - '@Claroline\AppBundle\API\TransferProvider'
                - method: setObjectManager
                  arguments:
                     - '@Claroline\AppBundle\Persistence\ObjectManager'
                - method: setSchema
                  arguments:
                     - '@Claroline\AppBundle\API\SchemaProvider'

        Claroline\AppBundle\API\Transfer\Action\AbstractDeleteAction:
            tags: [claroline.transfer.action]
            calls:
                - method: setCrud
                  arguments:
                     - '@Claroline\AppBundle\API\Crud'
                - method: setObjectManager
                  arguments:
                     - '@Claroline\AppBundle\Persistence\ObjectManager'

        Claroline\AppBundle\API\Transfer\Action\AbstractUpdateAction:
            tags: [claroline.transfer.action]
            calls:
                - method: setCrud
                  arguments:
                     - '@Claroline\AppBundle\API\Crud'

    # Directories
    Claroline\CoreBundle\API\Transfer\Action\Directory\Create:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@translator'

    Claroline\CoreBundle\API\Transfer\Action\Directory\CreateOrUpdate:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@translator'

    # Groups
    Claroline\CoreBundle\API\Transfer\Action\Group\Create: ~

    Claroline\CoreBundle\API\Transfer\Action\Group\Delete: ~

    Claroline\CoreBundle\API\Transfer\Action\Group\AddUser:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\Group\RemoveUser:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    # Users
    Claroline\CoreBundle\API\Transfer\Action\User\Create:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\User\CreateOrUpdate: ~

    Claroline\CoreBundle\API\Transfer\Action\User\Delete: ~

    Claroline\CoreBundle\API\Transfer\Action\User\Update:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\User\Enable:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\UserManager'

    Claroline\CoreBundle\API\Transfer\Action\User\Disable:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\UserManager'

    Claroline\CoreBundle\API\Transfer\Action\User\SetMainOrganization:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'

    # Workspaces
    Claroline\CoreBundle\API\Transfer\Action\Workspace\Create:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\Crud'
            - '@claroline.manager.workspace_manager'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\Delete: ~

    Claroline\CoreBundle\API\Transfer\Action\Workspace\Archive:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\Workspace\WorkspaceManager'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\Unarchive:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Manager\Workspace\WorkspaceManager'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\AddUser:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\RemoveUser:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\AddGroup:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Transfer\Action\Workspace\RemoveGroup:
        arguments:
            - '@Claroline\AppBundle\API\Crud'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
