ujm_exercise_open:
   pattern: /open/{exerciseId}
   defaults: { _controller: UJMExoBundle:Exercise:open }

ujm_exercise_paper:
    pattern:  /{id}/paper
    defaults: { _controller: "UJMExoBundle:Exercise:exercisePaper" }

ujm_exercise_paper_nav:
    pattern:  /paper/nav/
    defaults: { _controller: "UJMExoBundle:Exercise:exercisePaperNav" }
    requirements: { _method: post }
