imports:
    - { resource: services/command.yml }
    - { resource: services/controller.yml }
    - { resource: services/finder.yml }
    - { resource: services/subscriber.yml }
    - { resource: services/validator.yml }
    - { resource: services/updater.yml }
    - { resource: services/voter.yml }
