services:

    claroline.utilities.lipsum_generator:
        class: Claroline\CoreBundle\Library\Utilities\LipsumGenerator

    claroline.utilities.paginator_parser:
        class: Claroline\CoreBundle\Library\Utilities\PaginatorParser

    claroline.utilities.thumbnail_creator:
        class: Claroline\CoreBundle\Library\Utilities\ThumbnailCreator
        arguments:
          - "%kernel.root_dir%"
          - "%claroline.param.thumbnails_directory%"
          - "@claroline.resource.utilities"

    claroline.utilities.controller_name_parser:
        class: %controller_name_converter.class%
        arguments:
          - "@kernel"

    claroline.utilities.misc:
        class: Claroline\CoreBundle\Library\Utilities\ClaroUtilities