stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: '.tinymce'
    external_plugins:
            imagemanager:
                url: 'asset[bundles/clarolinecore/js/tinymce/config.js]'
    tinymce_buttons:
            ressourceLinker: # Id of the first button
                title: 'Resource Linker'
                image: 'http://claroline.net/favicon.ico'
    theme:
        simple:
            theme: 'modern'
            menubar: false
            toolbar1: 'bold italic underline | ressourceLinker | alignleft aligncenter alignright alignjustify'
        medium:
            theme: 'modern'
            plugins:
                     - ' preview, fullscreen, emoticons'
            menubar: false
            toolbar1: 'bold,italic,underline,undo,redo,removeformat,cleanup,code | ressourceLinker | preview '
            toolbar2: 'alignleft aligncenter alignright alignjustify | emoticons'
        advanced:
            plugins:
                - 'advlist autolink lists link image charmap print preview hr anchor pagebreak'
                - 'searchreplace wordcount visualblocks visualchars code fullscreen'
                - 'insertdatetime media nonbreaking save table contextmenu directionality'
                - 'emoticons template paste textcolor example'
            toolbar1: ' undo redo | styleselect | bold italic | -example'
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
