imports:
    - { resource: services/configuration.yml }
    - { resource: services/controller.yml }
    - { resource: services/finder.yml }
    - { resource: services/listener.yml }
    - { resource: services/manager.yml }
    - { resource: services/messenger.yml }
    - { resource: services/security.yml }
    - { resource: services/serializer.yml }
    - { resource: services/subscriber.yml }
    - { resource: services/updater.yml }
    - { resource: services/voter.yml }
