parameters:
    claroline.installation.bundle_file:          %kernel.root_dir%/config/bundles.ini
    claroline.installation_manager.class:        Claroline\InstallationBundle\Manager\InstallationManager
    claroline.installation_fixture_loader.class: Claroline\InstallationBundle\Fixtures\FixtureLoader
    claroline.symfony_fixture_loader.class:      Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader
    claroline.doctrine_fixture_executor.class:   Doctrine\Common\DataFixtures\Executor\ORMExecutor
