hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    resource_owners:
        dropbox:
            type:           dropbox
            client_id:      <client_id>
            client_secret:  <client_secret>
        facebook:
            type:           facebook
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          "email"
        github:
            type:           github
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          "user:email,public_repo"
        google:
            type:           google
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          "email profile"
        linkedin:
            type:           linkedin
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          "r_emailaddress r_basicprofile"
        office_365:
            type:           office365
            client_id:      <client_id>
            client_secret:  <client_secret>
        twitter:
            type:           twitter
            client_id:      <client_id>
            client_secret:  <client_secret>
            scope:          "email"
        windows_live:
            type:           windows_live
            client_id:      <client_id>
            client_secret:  <client_secret>

        generic:
            type:           oauth2
            client_id:      <client_id>
            client_secret:  <client_secret>
            access_token_url:    https://owner.domain.tld/oauth/v2/token
            authorization_url:   https://owner.domain.tld/oauth/v2/auth
            infos_url:           https://owner.domain.tld/api/user
            scope:               "user"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   username
                realname:   fullname
                username:   username



    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

#services:
#    hwi_oauth.user.provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

security:
    firewalls:
        main:
            logout:
                success_handler: Claroline\AuthenticationBundle\Security\Oauth\LogoutSuccessHandler
            oauth:
                oauth_user_provider:
                    service: Claroline\AuthenticationBundle\Security\Oauth\OauthUserProvider
                resource_owners:
                    dropbox:      /login/check-dropbox
                    facebook:     /login/check-facebook
                    github:       /login/check-github
                    google:       /login/check-google
                    linkedin:     /login/check-linkedin
                    office_365:   /login/check-o365
                    twitter:      /login/check-twitter
                    windows_live: /login/check-windows
                    generic:      /login/check-generic
                #success_handler:    Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler:    Claroline\AuthenticationBundle\Security\Oauth\FailureHandler
                login_path: /login
                failure_path: /login
                use_forward: false

