framework:
    secret:          %secret%
    router:
        resource: .
        type: dynamic
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }
    default_locale: %locale%
    session:
      save_path: %kernel.root_dir%/sessions
