hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    resource_owners:
        facebook:
            type:          facebook
            client_id:     <client_id>
            client_secret: <client_secret>
            scope:         "email"

    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

services:
    hwi_oauth.user.provider:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

security:
    firewalls:
        main:
            oauth:
                resource_owners:
                    facebook: /login/check_facebook
                login_path: /login
                failure_path: /login
                use_forward: false
                oauth_user_provider:
                    service: icap.oauth.facebook_provider
