imports:
    - { resource: services/command.yml }
    - { resource: services/controller.yml }
    - { resource: services/exporter.yml }
    - { resource: services/finder.yml }
    - { resource: services/manager.yml }
    - { resource: services/messenger.yml }
    - { resource: services/serializer.yml }
    - { resource: services/subscriber.yml }
    - { resource: services/updater.yml }
    - { resource: services/voter.yml }
